name: AutoRepair
main: com.mrockey28.bukkit.ItemRepair.AutoRepairPlugin
version: 2.15
authors: [mrockey28, lostaris]
softdepend: [Vault, PermissionsBukkit]
commands:
  repair:
    description: uses one or more items to repair a tool or armour
    aliases: [rep, ar]
    usage: |
      Incorrect usage of command /<command>.
      Proper usage of /<command>
       '/<command> [itemslot 1-9]' repair item.
       '/<command> [itemslot 1-9] ?' Check required repair materials.
       '/<command> [itemslot 1-9] dmg' Check number of uses left.
       '/<command> <?,dmg> as above but for current item.
       '/<command> arm' repairs all your equipped armour.
       '/<command> arm ?' Check armour repair materials.
       '/<command> all' Repair all items, if possible.
       '/<command> reload' Reloads the config files.
       
permissions:
  AutoRepair.access:
    description: Necessary for access to any repair commands 
    default: false
  AutoRepair.info:
    description: Allows use of the ? and dmg commands
    default: false
  AutoRepair.warn:
    description: Allows warning when a tool is about to break
    default: false
  AutoRepair.repair:
    description: Allows use of any repair mechanisms, assuming other required permissions are true
    default: false
  AutoRepair.repcommands:
    description: Allows use of repair console commands
    default: false
  AutoRepair.repair.enchanted:
    description: Allows repairing of enchanted weapons, when config is set to use permissions to configure this
    default: false
  AutoRepair.auto:
    description: Allows autorepair to work on users' items
    default: false
  AutoRepair.reload:
    description: Allows use of the reload command, to reload the config files
    default: false
  AutoRepair.itemgroup1:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup2:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup3:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup4:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup5:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup6:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup7:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup8:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  AutoRepair.itemgroup9:
    description: Allows restricting repair to certain sets of items, as specified by the configuration
    default: false
  